config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/destroy'

	get 'sessions/new'
	post 'sessions/create'
	get 'sessions/destroy'
	get 'sessions/login'
	get 'sessions/logout'
	get 'dashboard/show'
	get '/login' => 'sessions#new'
	get '/logout' => 'sessions#destroy'
	get 'market/show'
	post 'market/show'
	get 'profile/view'
	get 'profile/edit'
	post 'dashboard/show'
	get 'clients/show'
	post 'meetings/create'
	get "/calendar/show"
	post '/portfolios/add' => 'portfolios#add'
	post '/portfolios/sell' => 'portfolios#sell'
	post '/portfolios/:id' => 'portfolios#show'
	post '/clients/get_clients' => 'clients#get_clients'
	post '/meetings/update' => 'meetings#update'
	
	root to: 'sessions#new'

	resources :meetings
 	match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
	resources :clients
	resources :users
	resources :portfolios
	resources :users

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	belongs_to :user
	belongs_to :client

    validates :meeting_subject, presence: true,
				length: { 
					  minimum: 2,
					  maximum: 20,
					  too_short: "Must be longer title",
					  too_long: "Title too long"
					}

    validates :meeting_date ,presence: {message: "Date format incorrect. Enter in dd/mm/yyyy style"}
			#format: { with: /\A((((0[13578])|([13578])|(1[02]))[\/](([1-9])|([0-2][0-9])|(3[01])))|(((0[469])|([469])|(11))[\/](([1-9])|([0-2][0-9])|(30)))|((2|02)[\/](([1-9])|([0-2][0-9]))))[\/]\d{4}$|^\d{4}\z/}
	validates_uniqueness_of :meeting_date

	validates_presence_of :user_id

    validates :client_id, presence: true

    validates :meeting_description, length: { maximum: 1000 }
    def meeting_time
    	self.meeting_date.strftime("%I:%M%p")
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
    def index
         @meetings = Meeting.where("user_id = ?", session[:user_id])
         @meetings = @meetings.sort_by &:meeting_date
    end
    def show
        @meeting = Meeting.find_by_id(params[:id])
         if @meeting.nil? || @meeting.user_id != session[:user_id]
         #This can be replaced with a custom "permission denied" or "no such client" page
                 render :file => "/app/views/errors/error404.erb"
         end
    end

    def new
    	@clients = Client.where(user_id: session[:user_id]).order(:first_name, :last_name)

		@meeting = Meeting.new
    end

    def edit
        @clients = Client.where(user_id: session[:user_id]).order(:first_name, :last_name)
        @meeting = Meeting.find(params[:id])
    end
    
    def create
        @clients = Client.where(user_id: session[:user_id]).order(:first_name, :last_name)
		@meeting = Meeting.new(meeting_params)
		if @meeting.save
		    redirect_to '/meetings'
		else
		    redirect_to '/meetings/new'
		end
    end

    def update
        @clients = Client.where(user_id: session[:user_id]).order(:first_name, :last_name)
		@meeting = Meeting.find(params[:id])

		if @meeting.update(meeting_params)
		    redirect_to '/meetings'
		else
		    render 'edit'
		end
    end

    def destroy
		@meeting = Meeting.find(params[:id])
		@meeting.destroy

		redirect_to '/meetings'
    end

private

	def meeting_params
	    params.require(:meeting).permit(:meeting_subject, :meeting_date, :user_id, :client_id, :meeting_description).merge(user_id: session[:user_id])
	end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for @meeting do |f| %>
 
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@meeting.errors.count, "error") %> prohibited
        this meeting from being saved:
      </h2>
      <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :meeting_subject %><br>
    <%= f.text_field :meeting_subject %>
  </p>
 
  <p>
    <%= f.label :meeting_date_time %><br>
    <%= f.datetime_select :meeting_date_time, start_year:Date.today.year, :order => [:day,:month,:year], :minute_step => 15 %> 
  </p>

  <p>
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </p>

  <p>
    <%= f.label :meeting_description %><br>
    <%= f.text_area :meeting_description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/meetings/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1>Meetings</h1>
            <ol class="breadcrumb">
                <li>
                                <a href="/dashboard/show">Dashboard</a>
                            </li>
                <li>
                   <a href="/meetings">Meetings</a>
                </li>
                <li class="active">
                    Edit Meeting
                </li>
                            
            </ol>
    </div>
</div>



<div class="row">
  <div class="container-fluid">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 toppad" >
     
      
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Edit Meeting</h3>
        </div>
        <div class="panel-body">
          <div class="row">
                   
            
            <div class=" col-md-9 col-lg-9 "> 
              <%= form_for :meeting, url: meeting_path(@meeting),:html => { :class =>
                'table-user-information' }, method: :patch do |f| %>
              <table class="table table-user-information">
                <tbody>
                 <% if @meeting.errors.any? %>
                   <div id="error_explanation">
                    <h2>
                      <%= pluralize(@meeting.errors.count, "error") %> require fixing before this meeting can be saved:
                    </h2>
                    <ul>
                      <% @meeting.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
                  <% end %>
                <tr>
                  
                  <tr>
                    <td>Subject</td>
                    <td><%= f.text_field :meeting_subject %></td>
                    <%= f.hidden_field :user_id, value: session[:user_id] %>
                  </tr>
                 
                  <tr>
                    <td>Select Client</td>
                    <td><%= f.collection_select :client_id, @clients, :id, :full_name, prompt: "Please select a client..." %></td>
                  </tr>
                  <tr>
                    <td>Date of Meeting</td>
                    <td><%= f.datetime_select :meeting_date, start_year: Date.today.year, end_year: 2018 %></td>
                  </tr>
                  <tr>
                    <td>Meeting Notes</td>
                    <td> <%= f.text_area :meeting_description %></td>
                  </tr>
                  
                  
                </tbody>
              </table>
              <span class="pull-right">
              <%= f.submit class: "btn btn-info",data: { no_turbolink: true } %>
                <% end %>
                <a href="/meetings" data-original-title="Return" data-toggle="tooltip" type="button" class="btn btn-danger">Cancel </a>
              </span>
              
            </div>
          </div>
        </div>
      </div>                 
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1>Meetings</h1>
            <ol class="breadcrumb">
                <li>
                                <a href="/dashboard/show">Dashboard</a>
                            </li>
                <li class="active">
                    Meetings
                </li>
                            
            </ol>
    </div>
</div>

<div class="row">  
<div class="col-ld-12 col-md-8 container-fluid panel-default">              
    <div class="panel panel-primary no-curve">
        <div class="panel-heading clearfix no-curve">
            <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Meetings List</h4>
            <div class="input-group-btn">
                <a href="/meetings/new"><button class="btn btn-warning no-curve pull-right">Add Meeting</button></a>
            </div>  
        </div>

        <div class="panel-body">
        <div class="list-group">
        
         <div class="list-group">
                <% if !@meetings.nil? && @meetings.count > 1 %>
                <% @meetings.each do |meeting| %>
                            <h4 class="list-group-item-heading">Subject: <%= meeting.meeting_subject %></h4> <br/>
                            <p class="list-group-item-text">
                            Date: <%= meeting.meeting_date.strftime("%A, %B %d, %Y") %> <br/>
                            Client: <%= meeting.client.first_name + " " + meeting.client.last_name%> <br/>
                            Time: <%= meeting.meeting_date.strftime("%H:%M %p") %> <br/>
                            Meeting Notes: <%= meeting.meeting_description %>
                            </p>
                            <%= link_to 'Remove', meeting_path(meeting), method: :delete, data: { confirm: 'Are you sure you want to remove your meeting with '+meeting.client.first_name+'?' }, class: "btn btn-danger btn-xs" %>
                            <%= link_to 'Edit', edit_meeting_path(meeting), class: "btn btn-warning btn-xs" %>
                        </br></br>
                    <% end %>
                <% elsif !@meetings.nil? && @meetings.count == 1 %>
                            <h4 class="list-group-item-heading">Subject: <%= @meetings[0].meeting_subject %></h4> <br/>
                            <p class="list-group-item-text">
                            Date: <%= @meetings[0].meeting_date.strftime("%A, %B %d, %Y") %> <br/>
                            Client: <%= @meetings[0].client.first_name + " " + @meetings[0].client.last_name%> <br/>
                            Time: <%= @meetings[0].meeting_date.strftime("%H:%M %p") %> <br/>
                            Meeting Notes: <%= @meetings[0].meeting_description %>
                            </p>
                            <%= link_to 'Remove', meeting_path(@meetings[0]), method: :delete, data: { confirm: 'Are you sure you want to remove your meeting with '+@meetings[0].client.first_name+'?' }, class: "btn btn-danger btn-xs" %>
                            <%= link_to 'Edit', edit_meeting_path(@meetings[0]), class: "btn btn-warning btn-xs" %>
                        </br></br>
                <% else %>
                    No meetings currently...
                <% end %>
                
            
            </div>
        </div>
    </div>

</div>  
</div>

app/views/meetings/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1>Meetings</h1>
            <ol class="breadcrumb">
                <li>
                                <a href="/dashboard/show">Dashboard</a>
                            </li>
                <li>
                   <a href="/meetings">Meetings</a>
                </li>
                <li class="active">
                    New Meeting
                </li>
                            
            </ol>
    </div>
</div>



<div class="row">
  <div class="container-fluid">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 toppad" >
     
      
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Add New Meeting</h3>
        </div>
        <div class="panel-body">
          <div class="row">
                   
            
            <div class=" col-md-9 col-lg-9 "> 
              <%= form_for @meeting, url: "/meetings/create" do |f| %>
              <table class="table table-user-information">
                <tbody>
                <tr>
                  <tr>
                    <td>Subject</td>
                    <td><%= f.text_field :meeting_subject %></td>
                    <%= f.hidden_field :user_id, value: session[:user_id] %>
                  </tr>
                 
                  <tr>
                    <td>Select Client</td>
                    <td><%= f.collection_select :client_id, @clients, :id, :full_name, prompt: "Please select a client..." %></td>
                  </tr>
                  <tr>
                    <td>Date of Meeting</td>
                    <td><%= f.datetime_select :meeting_date, start_year: Date.today.year, end_year: 2018 %></td>
                  </tr>
                  <tr>
                    <td>Meeting Notes</td>
                    <td> <%= f.text_area :meeting_description %></td>
                  </tr>
                </tbody>
              </table>
              <span class="pull-right">
              <%= f.submit class: "btn btn-info" %>
                
                <% end %>
                <a href="/meetings" data-original-title="Return" data-toggle="tooltip" type="button" class="btn btn-danger">Cancel </a>
              </span>
              
            </div>
          </div>
        </div>
      </div>                 
    </div>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1>Meetings</h1>
            <ol class="breadcrumb">
                <li>
                                <a href="/dashboard/show">Dashboard</a>
                            </li>
                <li class="active">
                    Meetings
                </li>
                            
            </ol>
    </div>
</div>

<div class="row">  
<div class="col-ld-12 col-md-8 container-fluid panel-default">              
	<div class="panel panel-primary no-curve">
        <div class="panel-heading clearfix no-curve">
            <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Meeting Details</h4>
            <div class="input-group-btn">
                <a href="/meetings/<%=@meeting.id%>/edit"><button class="btn btn-warning no-curve pull-right">Edit Meeting</button></a>
            </div>  
        </div>

        <div class="panel-body">
        <div class="list-group">
<<<<<<< HEAD
        

        		<% if !@meetings.nil? && @meetings.count > 1 %>
        			 <% @meetings.each do |meeting| %>
                     <a class="list-group-item">
        				<h4 class="list-group-item-heading">Subject: <%= meeting.meeting_subject %></h4> <br/>
                        <p class="list-group-item-text">
        				Date: <%= meeting.meeting_date.strftime("%A, %B %d, %Y") %> <br/>
        				Client: <%= meeting.client.first_name + " " + meeting.client.last_name %> <br/>
                        		Time: <%= meeting.meeting_date.strftime("%H:%M %p") %> <br/>
        				Meeting Description: <%= meeting.meeting_description %>
                        </p>
                        <%= link_to 'Remove', meeting_path(meeting), method: :delete, data: { confirm: 'Are you sure you want to remove your meeting with '+meeting.client_name+'?' }, class: "btn btn-danger btn-xs" %>
                        </a>
                        </br>
                        </br>
        			<% end %>
                   
                <% elsif @meetings.count == 1 %>
                    Subject: <%= @meetings[0].meeting_subject %> <br/>
                    Date: <%= @meetings[0].meeting_date.strftime("%A, %B %d, %Y") %> <br/>
                    Time: <%= @meetings[0].meeting_date.strftime("%H:%M %p") %> <br/>
                    Client: <%= @meetings[0].client.first_name + " " + @meetings[0].client.last_name %> <br/>
                    Meeting Description: <%= @meetings[0].meeting_description %>
                     <a class="list-group-item">
        				<h4 class="list-group-item-heading">Subject: <%= @meeting.meeting_subject %></h4> <br/>
                        <p class="list-group-item-text">
        				Date: <%= @meeting.meeting_date.strftime("%A, %B %d, %Y") %> <br/>
        				Client: <%= @meeting.client.first_name+" "+@meeting.client.last_name %> <br/>
                        Time: <%= @meeting.meeting_date.strftime("%H:%M %p") %> <br/>
        				Meeting Description: <%= @meeting.meeting_description %>
                        </p>
                        <%= link_to 'Remove', meeting_path(meeting), method: :delete, data: { confirm: 'Are you sure you want to remove your meeting with '+meeting.client_name+'?' }, class: "btn btn-danger btn-xs" %>
                        </a>
                        </br>
                        </br>
                    <% end %>
                <% else %>
                    No meetings currently...
                <% end %>
                
        	
            </div>
                        <%= link_to 'Remove', meeting_path(@meeting), method: :delete, data: { confirm: 'Are you sure you want to remove your meeting with '+@meeting.client.first_name+'?' }, class: "btn btn-danger btn-xs" %>
                        </a>        	
 
        </div>
    </div>

</div>	
</div>
</div>