config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  get 'users/create'

  get 'users/edit'

  get 'users/destroy'

	get 'sessions/new'
	post 'sessions/create'
	get 'sessions/destroy'
	get 'sessions/login'
	get 'sessions/logout'
	get 'dashboard/show'
	get '/login' => 'sessions#new'
	get '/logout' => 'sessions#destroy'
	get 'market/show'
	post 'market/show'
	get 'profile/view'
	get 'profile/edit'
	post 'dashboard/show'
	get 'clients/show'
	post 'meetings/create'
	get "/calendar/show"
	post '/portfolios/add' => 'portfolios#add'
	post '/portfolios/sell' => 'portfolios#sell'
	post '/portfolios/:id' => 'portfolios#show'
	post '/clients/get_clients' => 'clients#get_clients'
	post '/meetings/update' => 'meetings#update'
	
	root to: 'sessions#new'

	resources :meetings
 	match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
	resources :clients
	resources :users
	resources :portfolios
	resources :users

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :meetings, dependent: :destroy
	has_many :shares
	has_many :owned_shares, dependent: :destroy
	has_many :shares, through: :owned_shares
    belongs_to :user
	validates :first_name, presence: true, length: {minumum: 1, maximum: 30}, format: {without: /[0-9]/}
	validates :last_name, presence: true, length: {minumum: 1, maximum: 30}, format: {without:/[0-9]/}

    validates_uniqueness_of :last_name, :scope => [:first_name, :address], :message => ('implies that a client with these details already exists in the database')
	validates_uniqueness_of :email, :scope => [:first_name, :last_name], :message => ('implies that a client with these details already exists in the database')
	validates :dob, presence: true
	validates :address, presence: true, length: {minimum: 3, maximum: 50}
	validates :email, presence: true, length: {minumum: 4, maximum: 30}, format: {with: /[-0-9a-zA-Z.+_]+@[-0-9a-zA-Z.+_]+\.[a-zA-Z]{2,4}/}
	validates :home_tel, presence: true, length: {minimum: 10, maximum: 15}, numericality: :only_integer
    validates :mobile_tel, :allow_blank => true, length: {minimum: 10, maximum: 15}, numericality: :only_integer

	def full_name
		self.first_name + " " + self.last_name
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
		@clients = Client.where("user_id = ?", session[:user_id])
		@users = User.all.order(:firstname, :surname)
		if @user.access_level > 1
			@clients = Client.all
		end
	end
	def show
		@client = Client.find_by_id(params[:id])
		@users = User.all.order(:firstname, :surname)
		if (@client.nil? || @client.user_id != session[:user_id]) && @user.access_level<2
			#This can be replaced with a custom "permission denied" or "no such client" page
			render :file => "/app/views/errors/error404.erb"
		end	
	end
	def new
		@users = User.all.order(:firstname, :surname)
		@client = Client.new
	end
	def get_clients
		unless params[:client_name].nil?
			#t = Client.arel_table
			#@clients = User.find(session[:user_id]).clients.where(t[:name].matches("%#{params[:client_name]}%"))
			@clients = User.find(session[:user_id]).clients.where("lower(first_name) LIKE ? OR lower(last_name) LIKE ? OR lower((select concat(first_name, ' ', last_name))) LIKE ?", "%#{params[:client_name].downcase}%", "%#{params[:client_name].downcase}%", "%#{params[:client_name].downcase}%")
			render json: @clients
		else
			render json: "{\"error\" : \"No user specified...\"}"
		end
	end
	def edit
		@users = User.all.order(:firstname, :surname)
		@client = Client.find(params[:id])
	end
	def update
		@users = User.all.order(:firstname, :surname)
		@client = Client.find(params[:id])
		if @client.update(client_params)
			redirect_to @client
		else
			render 'edit'
		end
	end
	def create
		@users = User.all.order(:firstname, :surname)
		@client = Client.new(client_params)
		@client.user_id = session[:user_id]
		if @client.save
			redirect_to @client
		else
			render 'new'
		end
	end
	def destroy
		@client = Client.find(params[:id])
		@client.user_id = nil
 		@client.save
 		if @user.access_level > 1
			@client.destroy
		end
		redirect_to clients_path			
	end
	private
	def client_params
		params.require(:client).permit(:first_name, :last_name, :dob, :address, :home_tel, :mobile_tel, :email, :title, :user, :user_id)	
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/denied.html.erb
<div class="row">
 <div class="col-lg-12">
  <h1 class="page-header">
    Clients
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="/dashboard/show">Dashboard</a>
    </li>
    <li>
      <a href="/clients">Clients</a>
    </li>
    <li class="active">
      New Client
    </li>
  </ol>
</div>
</div>

<div class="row">
  <div class="container-fluid">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 toppad" >
     
      
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Edit Client</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle"> </div>
            
            
            <div class=" col-md-9 col-lg-9 "> 
              <%= form_for :client,:html => { :class =>
                'table-user-information' }, url: clients_path do |f| %>
              <table class="table table-user-information">
                <tbody>
                 
                 <% if @client.errors.any? %>
                 <div id="error_explanation">
                  <h2>
                    <%= pluralize(@client.errors.count, "error") %> require fixing before this client can be saved:
                  </h2>
                  <ul>
                    <% @client.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
                
                <tr>
                  
                  <tr>
                    <td>Title</td>
                    <td><%= f.select :title, options_for_select([["Mr","Mr"],["Mrs","Mrs"],["Miss","Miss"], ["Ms","Ms"],["Dr","Dr"]],1) %></td>
                  </tr>
                  <tr>
                    <td>First Name</td>
                    <td><%= f.text_field :first_name,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Last Name</td>
                    <td><%= f.text_field :last_name,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Date of Birth</td>
                    <td><%= f.date_select :dob, start_year:1920, end_year:Date.today.year, :class => 'datepicker' %></td>
                  </tr>
                  <tr>
                    <td>Address</td>
                    <td> <%= f.text_field :address,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Home Telephone</td>
                    <td><%= f.telephone_field :home_tel,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Mobile Telephone</td>
                    <td><%= f.telephone_field :mobile_tel,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Email</td>
                    <td><%= f.email_field :email,class: "form-control" %></td>
                  </tr>
                  
                </tbody>
              </table>
              <span class="pull-right">
                <%= f.submit class: "btn btn-success", data: { no_turbolink: true }%>
                <% end %>
                <a href="/clients" data-original-title="Return" data-toggle="tooltip" type="button" class="btn btn-danger">Cancel </a>
              </span>
              
            </div>
          </div>
        </div>
      </div>                 
    </div>
  </div>
</div>

app/views/clients/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Clients
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="/dashboard/show">Dashboard</a>
      </li>
      <li>
        <a href="/clients">Clients</a>
      </li>
      <li class="active">
        Edit
      </li>
    </ol>
  </div>
</div>




<div class="row">
  <div class="container-fluid">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 toppad" >
     
      
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Edit Client</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle"> </div>
            
            
            <div class=" col-md-9 col-lg-9 "> 
              <%= form_for :client, url: client_path(@client),:html => { :class =>
                'table-user-information' }, method: :patch do |f| %>
                <table class="table table-user-information">
                  
                  <tbody>
                   
                   <% if @client.errors.any? %>
                   <div id="error_explanation">
                    <h2>
                      <%= pluralize(@client.errors.count, "error") %> require fixing before this client can be saved:
                    </h2>
                    <ul>
                      <% @client.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
                  <% end %>
                  
                  <tr>
                    
                    <tr>
                      <td>Title</td>
                      <td><%= f.select :title, ["Mr","Mrs","Miss","Ms","Dr"] %></td>
                    </tr>
                    <tr>
                      <td>First Name</td>
                      <td><%= f.text_field :first_name,class: "form-control" %></td>
                    </tr>
                    <tr>
                      <td>Last Name</td>
                      <td><%= f.text_field :last_name,class: "form-control" %></td>
                    </tr>
                    <tr>
                      <td>Date of Birth</td>
                      <td><%= f.date_select :dob, start_year:1920, end_year:Date.today.year, :class => 'datepicker' %></td>
                    </tr>
                    <tr>
                      <td>Address</td>
                      <td> <%= f.text_field :address,class: "form-control" %></td>
                    </tr>
                    <tr>
                      <td>Home Telephone</td>
                      <td><%= f.telephone_field :home_tel,class: "form-control" %></td>
                    </tr>
                    <tr>
                      <td>Mobile Telephone</td>
                      <td><%= f.telephone_field :mobile_tel,class: "form-control" %></td>
                    </tr>
                    <tr>
                      <td>Email</td>
                      <td><%= f.email_field :email,class: "form-control" %></td>
                    </tr>
                    <% if @user.access_level > 1 %>
                    <tr>
                      <td>Financial Advisor</td>
                      <td><%= f.collection_select :user_id, @users, :id, :fullname, prompt: "Please select a user.." %></td>
                    </tr>
                   <% end %>
                  </tbody>
                </table>
                <span class="pull-right">
                  <%= f.submit class: "btn btn-success", data: { no_turbolink: true } %>
                  <% end %>
                  <a href="/clients" data-original-title="Return" data-toggle="tooltip" type="button" class="btn btn-warning">Discard Changes </a>
                </span>
                
              </div>
            </div>
          </div>
        </div>                 
      </div>
    </div>
  </div>

app/views/clients/get_clients.html.erb
<h1>Clients#get_clients</h1>
<p>Find me in app/views/clients/get_clients.html.erb</p>

app/views/clients/index.html.erb
<div class="row">
 <div class="col-lg-12">
  <h1 class="page-header">
    <% if @user.access_level > 1 %>
       All Clients
    <% else %>
       Clients
    <% end %>
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="/dashboard/show">Dashboard</a>
    </li>
    <li class="active">
      Clients
    </li>
  </ol>
</div>
</div>

<div class="col-xs-12 col-md-9 container-fluid panel-default">

  <div class="panel panel-primary">
    <div class="panel-heading clearfix ">
      <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Client List</h4>
      <div class="input-group col-md-offset-6 col-xs-offset-8">
        <div class="input-group-btn"></i></button>&nbsp;
          <div class="divider"></div>
          <a href="/clients/new"><button class="btn btn-primary no-curve pull-right">Add Client</button></a>
          
        </div>
      </div>
    </div>
    <div class="panel-body">
      <table class="table table-hover">
       <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @clients.each do |client| %>
      <tr> 
        <td><%= client.first_name %> <%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client_path(client), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Edit', edit_client_path(client), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Portfolio', portfolio_path(client), class: "btn btn-success btn-xs" %></td>
        <td><%= link_to 'Delete', client_path(client),
        method: :delete,
        data: { confirm: "Are you sure you want to delete "+ client.first_name + " " + client.last_name + "?"}, class: "btn btn-danger btn-xs" %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

</div>
</div>

app/views/clients/new.html.erb
<div class="row">
 <div class="col-lg-12">
  <h1 class="page-header">
    Clients
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="/dashboard/show">Dashboard</a>
    </li>
    <li>
      <a href="/clients">Clients</a>
    </li>
    <li class="active">
      New Client
    </li>
  </ol>
</div>
</div>

<div class="row">
  <div class="container-fluid">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 toppad" >
     
      
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">New Client</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle"> </div>
            
            
            <div class=" col-md-9 col-lg-9 "> 
              <%= form_for :client,:html => { :class =>
                'table-user-information' }, url: clients_path do |f| %>
              <table class="table table-user-information">
                <tbody>
                 
                 <% if @client.errors.any? %>
                 <div id="error_explanation">
                  <h2>
                    <%= pluralize(@client.errors.count, "error") %> require fixing before this client can be saved:
                  </h2>
                  <ul>
                    <% @client.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
                
                <tr>
                  
                  <tr>
                    <td>Title</td>
                    <td><%= f.select :title, options_for_select([["Mr","Mr"],["Mrs","Mrs"],["Miss","Miss"], ["Ms","Ms"],["Dr","Dr"]],1) %></td>
                  </tr>
                  <tr>
                    <td>First Name</td>
                    <td><%= f.text_field :first_name,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Last Name</td>
                    <td><%= f.text_field :last_name,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Date of Birth</td>
                    <td><%= f.date_select :dob, start_year:1920, end_year:Date.today.year, :class => 'datepicker' %></td>
                  </tr>
                  <tr>
                    <td>Address</td>
                    <td> <%= f.text_field :address,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Home Telephone</td>
                    <td><%= f.telephone_field :home_tel,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Mobile Telephone</td>
                    <td><%= f.telephone_field :mobile_tel,class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Email</td>
                    <td><%= f.email_field :email,class: "form-control" %></td>
                  </tr>
                </tbody>
              </table>
              <span class="pull-right">
                <%= f.submit class: "btn btn-success", data: { no_turbolink: true }%>
                <% end %>
                <a href="/clients" data-original-title="Return" data-toggle="tooltip" type="button" class="btn btn-danger">Cancel </a>
              </span>
              
            </div>
          </div>
        </div>
      </div>                 
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="row">
                     <div class="col-lg-12">
                        <h1 class="page-header">
                            Clients
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <a href="/dashboard/show">Dashboard</a>
                            </li>
                            <li>
                                <a href="/clients">Clients</a>
                            </li>
                            <li class="active">
                                Show
                            </li>
                        </ol>
                    </div>
                </div>

<div class="row">
      <div class="container-fluid">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 toppad" >
   
   		
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Client Details</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle"> </div>
                
                
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                     
                   
                        <tr>
                        <td>Title</td>
                        <td><%= @client.title %></td>
                      </tr>
                      <tr>
                        <td>First Name</td>
                        <td><%= @client.first_name %></td>
                      </tr>
                      <tr>
                        <td>Last Name</td>
                        <td><%= @client.last_name %></td>
                      </tr>
                      <tr>
                        <td>Date of Birth</td>
                        <td><%= @client.dob %></td>
                      </tr>
                      <tr>
                        <td>Address</td>
                        <td><%= @client.address %></td>
                      </tr>
                      <tr>
                        <td>Home Telephone</td>
                        <td><%= @client.home_tel %></td>
                      </tr>
                      <tr>
                        <td>Mobile Telephone</td>
                        <td><%= @client.mobile_tel %></td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><%= @client.email %></td>
                      </tr>
                      <% if @user.access_level > 1 %>
                    <tr>
                      <td>User</td>
                      <td><%= @client.user.firstname + " " + @client.user.surname %></td>
                    </tr>
                      <% end %>
                      
                     
                    </tbody>
                  </table>
                  <span class="pull-right">
                  	<%= link_to 'Edit', edit_client_path(@client), class: "btn btn-warning" %>
                  <%= link_to 'Back to Client List', clients_path, class: "btn btn-primary" %>
                  <%= link_to 'Portfolio', portfolio_path(@client), class: "btn btn-success" %>
                  <% if @user.access_level > 1 %>
       <%= link_to 'Delete', client_path(@client),
        method: :delete,
        data: { confirm: "Are you sure you want to delete "+ @client.first_name + " " + @client.last_name + " all of their meetings will be removed?"}, class: "btn btn-danger" %>
       <% else %>
       <%= link_to 'Delete', client_path(@client),
        method: :delete,
        data: { confirm: "Are you sure you want to delete "+ @client.first_name + " " + @client.last_name + "?"}, class: "btn btn-danger" %>
       <% end %>
                </span>
                </div>
              </div>
            </div>
           </div>                 
          </div>
        </div>
      </div>